- name: Commit and Push if changed
  run: |
    git config --global user.name "github-actions"
    git config --global user.email "github-actions@github.com"
    git add README.md
    git commit -m "Updated README with GitHub Stats" || echo "No changes to commit"
    git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/ahmed-on391/ahmed-on391.git
