name: Update README with GitHub Stats

on:
  schedule:
    - cron: "0 * * * *"  # تحديث كل ساعة
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: anuraghazra/github-readme-stats@v1
      - run: echo "README updated"
